/**
 * Constantes utilisées dans l'application
 */

const USER_ROLES = {
  SENDER: 'SENDER',
  TRAVELER: 'TRAVELER',
  BOTH: 'BOTH'
};

const USER_STATUS = {
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  VERIFIED: 'VERIFIED',
  SUSPENDED: 'SUSPENDED',
  INACTIVE: 'INACTIVE'
};

const SHIPMENT_STATUS = {
  PENDING_MATCH: 'PENDING_MATCH',
  MATCHED: 'MATCHED',
  IN_TRANSIT: 'IN_TRANSIT',
  DELIVERED: 'DELIVERED',
  CANCELED: 'CANCELED'
};

const TRIP_STATUS = {
  AVAILABLE: 'AVAILABLE',
  PARTIALLY_BOOKED: 'PARTIALLY_BOOKED',
  FULLY_BOOKED: 'FULLY_BOOKED',
  COMPLETED: 'COMPLETED',
  CANCELED: 'CANCELED'
};

const TRANSACTION_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  IN_PROGRESS: 'IN_PROGRESS',
  DELIVERED: 'DELIVERED',
  DISPUTED: 'DISPUTED',
  CANCELED: 'CANCELED',
  COMPLETED: 'COMPLETED'
};

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  REFUNDED: 'REFUNDED',
  FAILED: 'FAILED'
};

const NOTIFICATION_TYPES = {
  SHIPMENT_MATCHED: 'SHIPMENT_MATCHED',
  TRIP_BOOKED: 'TRIP_BOOKED',
  DELIVERY_CONFIRMED: 'DELIVERY_CONFIRMED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  REVIEW_RECEIVED: 'REVIEW_RECEIVED',
  SYSTEM_ALERT: 'SYSTEM_ALERT'
};

const REVIEW_TYPES = {
  SENDER_TO_TRAVELER: 'SENDER_TO_TRAVELER',
  TRAVELER_TO_SENDER: 'TRAVELER_TO_SENDER'
};

export {
  USER_ROLES,
  USER_STATUS,
  SHIPMENT_STATUS,
  TRIP_STATUS,
  TRANSACTION_STATUS,
  PAYMENT_STATUS,
  NOTIFICATION_TYPES,
  REVIEW_TYPES
};